-- 코드를 입력하세요
-- SELECT
--     BBS.AUTHOR_ID,
--     A.AUTHOR_NAME,
--     BBS.CATEGORY,
--     BBS.TOTAL_SALES
-- FROM AUTHOR A
-- INNER JOIN
-- (SELECT
--     B.BOOK_ID,
--     B.PRICE * BS.SALE_COUNT AS TOTAL_SALES,
--     B.AUTHOR_ID,
--     B.CATEGORY
-- FROM BOOK B
-- INNER JOIN
-- (SELECT
--     BOOK_ID,
--     SUM(SALES) AS SALE_COUNT
-- FROM
--     BOOK_SALES
-- WHERE
--     TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
-- GROUP BY BOOK_ID) BS
-- ON B.BOOK_ID = BS.BOOK_ID) BBS
-- ON A.AUTHOR_ID = BBS.AUTHOR_ID
-- ORDER BY A.AUTHOR_ID, BBS.CATEGORY DESC;
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS SALES
FROM 
    BOOK_SALES BS
INNER JOIN
    BOOK B ON BS.BOOK_ID = B.BOOK_ID
INNER JOIN
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY 
    B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, B.CATEGORY DESC;
