-- 코드를 입력하세요
SELECT
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
    (
    SELECT
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        8 <= EXTRACT(MONTH FROM START_DATE) 
        AND 
        EXTRACT(MONTH FROM START_DATE) < 11
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
    ) 
    AND 
        8 <= EXTRACT(MONTH FROM START_DATE) 
        AND 
        EXTRACT(MONTH FROM START_DATE) < 11
GROUP BY CAR_ID, EXTRACT(MONTH FROM START_DATE)
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH, CAR_ID DESC;

